# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_repo_name": "00_gh.ipynb",
         "get_base_repo_url": "00_gh.ipynb",
         "write_gh_template": "00_gh.ipynb",
         "get_last_tag": "00_gh.ipynb",
         "get_commit_msgs": "00_gh.ipynb",
         "add_pull_request_link": "00_gh.ipynb",
         "release_report": "00_gh.ipynb",
         "get_gh_credentials": "00_gh.ipynb",
         "get_tags": "00_gh.ipynb",
         "get_gh_config": "00_gh.ipynb",
         "make_gh_release": "00_gh.ipynb",
         "make_changelog": "00_gh.ipynb",
         "clean_dist": "01_pypi.ipynb",
         "build_pypi_package": "01_pypi.ipynb",
         "publish_pypi_package": "01_pypi.ipynb",
         "build_and_publish_pypi": "01_pypi.ipynb",
         "read_meta_template": "02_conda.ipynb",
         "update_meta_yaml": "02_conda.ipynb",
         "build_conda_package": "02_conda.ipynb",
         "login_to_anaconda": "02_conda.ipynb",
         "upload_conda_package": "02_conda.ipynb",
         "init_configs": "03_cli.ipynb",
         "make_gh_release_cli": "03_cli.ipynb",
         "check_git_dir": "04_utils.ipynb",
         "check_project_root": "04_utils.ipynb",
         "read_credentials": "04_utils.ipynb",
         "get_config": "04_utils.ipynb",
         "get_template": "04_utils.ipynb",
         "update_gitignore": "04_utils.ipynb",
         "write_settings_ini": "04_utils.ipynb",
         "write_setup_py": "04_utils.ipynb",
         "write_conda_build_scripts": "04_utils.ipynb",
         "get_conda_env_packages": "04_utils.ipynb",
         "get_anaconda_credentials": "04_utils.ipynb",
         "get_pypi_credentials": "04_utils.ipynb",
         "write_init_version": "04_utils.ipynb",
         "run_tests": "04_utils.ipynb"}

modules = ["gh.py",
           "pypi.py",
           "conda.py",
           "cli.py",
           "utils.py"]

doc_url = "https://PabloRMira.github.io/easyrelease/"

git_url = "https://github.com/PabloRMira/easyrelease/tree/main/"

def custom_doc_links(name): return None
