# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"write_gh_template": "00_core.ipynb",
         "get_last_tag": "00_core.ipynb",
         "get_commit_msgs": "00_core.ipynb",
         "get_config": "00_core.ipynb",
         "get_release_version": "00_core.ipynb",
         "add_pull_request_link": "00_core.ipynb"}

modules = ["gh.py"]

doc_url = "https://PabloRMira.github.io/easyrelease/"

git_url = "https://github.com/PabloRMira/easyrelease/tree/main/"

def custom_doc_links(name): return None
