# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['write_gh_template', 'get_last_tag', 'get_commit_msgs', 'get_config', 'get_release_version',
           'add_pull_request_link']

# Cell
import os
import re
import pkgutil
import subprocess
from configparser import ConfigParser

# Cell
def write_gh_template():
    "Write GitHub template for assigning commit messages to categories"
    template = pkgutil.get_data(__name__, "templates/gh_release.yaml").decode("utf-8")
    with open(".gh_release.yaml", "w") as f:
        f.write(template)

# Cell
def get_last_tag():
    "Get latest git tag"
    return subprocess.run(["git", "describe", "--tags", "--abbrev=0"],
                          capture_output=True).stdout.decode("utf").strip()

# Cell
def get_commit_msgs(from_tag=None, to="HEAD"):
    "Get commits `from_tag` to `to`"
    last_tag = from_tag if from_tag is not None else get_last_tag()
    commit_msgs = subprocess.run(["git", "log", f"{last_tag}..{to}", "--pretty=%s"],
                          capture_output=True).stdout.decode("utf").strip()
    return commit_msgs.split("\n")

# Cell
def get_config():
    "Get config from settings.ini"
    config = ConfigParser(delimiters=['='])
    config.read('settings.ini')
    cfg = config['DEFAULT']
    return cfg

# Cell
def get_release_version():
    "Get release version from settings.ini"
    cfg = get_config()
    return cfg["version"]

# Cell
def add_pull_request_link(msg):
    "Add pull request link to commit message `s` if reference is found, e.g. #100"
    cfg = get_config()
    git_url = cfg["git_url"]
    msg_with_link = re.sub("(#)(\d+)", rf"[\1\2]({git_url}/pull/\2)", msg)
    return msg_with_link