gh_categories:
    - title: "### Bugfixes:"
        keyword: "[FIX]"
    - title: "### New features:"
        keyword: "[FEA]"
    - title: "### Documentation:"
        keyword: "[DOC]"
    - title: "### Refactoring / Maintenance:"
        keyword: "[MNT]"
